# .github/workflows/cd.yml
name: CD - Deploy to Staging & Production

on:
  push:
    branches: [main, develop]

jobs:
  # Paso 1: Build para Deploy
  build:
    name: 'Build Assets for Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production assets
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-assets-${{ github.sha }}
          path: public/build/
          retention-days: 1

  # Paso 2: Deploy to Staging
  deploy-staging:
    name: 'Deploy to Staging'
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-assets-${{ github.sha }}
          path: public/build/

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host key
        run: ssh-keyscan -H ssh.gb.stackcp.com >> ~/.ssh/known_hosts

      - name: Deploy to staging
        run: |
          chmod +x .github/scripts/deploy-staging.sh
          .github/scripts/deploy-staging.sh

  # Paso 3: Deploy to Production
  deploy-production:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: production # Requires manual approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-assets-${{ github.sha }}
          path: public/build/

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host key
        run: ssh-keyscan -H ssh.gb.stackcp.com >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: |
          chmod +x .github/scripts/deploy-production.sh
          .github/scripts/deploy-production.sh
